#print((1.0 == 1.0) + "\n");
#print((1.0 != 1.0) + "\n");
#print((2.0 > 1.0) + "\n");
#print((1 >= 1) + "\n");
#print((1 < 1) + "\n");
#print((1 <= 1) + "\n");
#print("str1" == "str");
#print("str2" != null);
print(false && true);
print(1 || false);
